info:
    component: Assesment Api Gateway
zuul:
  routes:
    dotnet-api:
       path: /dotnet-api/**
       service-id: dotnet-api
    
---
hystrix:
  command:
    default:
      execution:  
        timeout:
          enabled: false      
      
       